language: java
jdk:
  - oraclejdk8
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
addons:
  sonarcloud:
    organization: "jhonatancarvalho-github"
    token:
      secure: e38f289fd361e6741dad6f8b0b1d9dc1473df67b
script:
  - mvn test
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar
after_success:
  - bash <(curl -s https://codecov.io/bash)