language: java
jdk:
  - oraclejdk8
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
addons:
  sonarcloud:
    organization: "jhonatancarvalho-github"
script:
  - mvn test
cache:
  directories:
  - $HOME/.m2
after_success:
  - bash <(curl -s https://codecov.io/bash)