ignore:
  - "src/main/java/br/com/jhonatan/encat/config/.*"
  - "src/main/java/br/com/jhonatan/encat/domain/.*"
  - "src/main/java/br/com/jhonatan/encat/dto/.*"
  - "src/main/java/br/com/jhonatan/encat/repositories/.*"
  - "src/main/java/br/com/jhonatan/encat/recources/.*"
  - "src/main/java/br/com/jhonatan/encat/services/exceptions/.*"
  - "src/main/java/br/com/jhonatan/encat/EncatApplication.java"